apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amazone-gateway
  namespace: argocd
spec:
  project: amazone
  source:
    repoURL: "https://github.com/killiankopp/gateway.cicd.git"
    targetRevision: main
    path: CD/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: amazone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true